(swank:set-default-directory "/home/jfh/code/lisp/source/web/todo/todo-project/")
(push #p"/home/jfh/code/lisp/source/util-lib/web/jfh-web/" asdf:*central-registry*)
(push #p"/home/jfh/code/lisp/source/util-lib/testing/jfh-testing/" asdf:*central-registry*)
(push #p"/home/jfh/code/lisp/source/util-lib/web/test/jfh-web-test/" asdf:*central-registry*)
(push #p"/home/jfh/code/lisp/source/web/todo/todo-project/" asdf:*central-registry*)
(asdf:load-system "jfh-web")
(compile-file #p"/home/jfh/code/lisp/source/util-lib/web/jfh-web/jfh-web.lisp")
(asdf:load-system "jfh-testing")
(asdf:load-system "jfh-web-test")
(asdf:load-system "todo-project")
(in-package #:todo-project)
